version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3

  - package-ecosystem: "bun"
    directory: "/web/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:45"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
