//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AdapterManifestConfigFieldsType.
const (
	Bool   AdapterManifestConfigFieldsType = "bool"
	Int    AdapterManifestConfigFieldsType = "int"
	String AdapterManifestConfigFieldsType = "string"
)

// Valid indicates whether the value is a known member of the AdapterManifestConfigFieldsType enum.
func (e AdapterManifestConfigFieldsType) Valid() bool {
	switch e {
	case Bool:
		return true
	case Int:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for CreateConnectionRequestCredentialSource.
const (
	Env      CreateConnectionRequestCredentialSource = "env"
	Mercator CreateConnectionRequestCredentialSource = "mercator"
)

// Valid indicates whether the value is a known member of the CreateConnectionRequestCredentialSource enum.
func (e CreateConnectionRequestCredentialSource) Valid() bool {
	switch e {
	case Env:
		return true
	case Mercator:
		return true
	default:
		return false
	}
}

// Defines values for RunCleanup.
const (
	Blocked     RunCleanup = "blocked"
	Confirmed   RunCleanup = "confirmed"
	NotRequired RunCleanup = "not_required"
	Pending     RunCleanup = "pending"
)

// Valid indicates whether the value is a known member of the RunCleanup enum.
func (e RunCleanup) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Confirmed:
		return true
	case NotRequired:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for RunDisposition.
const (
	Release   RunDisposition = "release"
	Terminate RunDisposition = "terminate"
)

// Valid indicates whether the value is a known member of the RunDisposition enum.
func (e RunDisposition) Valid() bool {
	switch e {
	case Release:
		return true
	case Terminate:
		return true
	default:
		return false
	}
}

// Defines values for RunOutcome.
const (
	Cancelled RunOutcome = "cancelled"
	Failed    RunOutcome = "failed"
	Succeeded RunOutcome = "succeeded"
)

// Valid indicates whether the value is a known member of the RunOutcome enum.
func (e RunOutcome) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Failed:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// AdapterListResponse defines model for AdapterListResponse.
type AdapterListResponse struct {
	Adapters []AdapterManifest `json:"adapters"`
}

// AdapterManifest An adapter's self-description for onboarding surfaces. Lives next to the adapter's code; carries no per-connection state and never any secret material.
type AdapterManifest struct {
	ConfigFields []struct {
		Default     *string `json:"default,omitempty"`
		Help        *string `json:"help,omitempty"`
		Label       string  `json:"label"`
		Name        string  `json:"name"`
		Placeholder *string `json:"placeholder,omitempty"`
		Required    bool    `json:"required"`

		// Secret Mask in UIs and never echo after save.
		Secret *bool                           `json:"secret,omitempty"`
		Type   AdapterManifestConfigFieldsType `json:"type"`
	} `json:"config_fields"`
	Credential struct {
		// Format One-line hint about the expected token shape or scope.
		Format   *string `json:"format,omitempty"`
		Label    *string `json:"label,omitempty"`
		Required bool    `json:"required"`
	} `json:"credential"`
	Description string `json:"description"`
	DisplayName string `json:"display_name"`

	// Logo Well-known slug the console maps to a bundled logomark asset; consumers fall back to a typographic monogram.
	Logo string `json:"logo"`

	// SetupSteps Ordered how-do-I-get-a-credential walkthrough; text is UI copy.
	SetupSteps []struct {
		Text string  `json:"text"`
		Url  *string `json:"url,omitempty"`
	} `json:"setup_steps"`

	// Type Adapter type string used as adapter_type at connection create time.
	Type string `json:"type"`
}

// AdapterManifestConfigFieldsType defines model for AdapterManifest.ConfigFields.Type.
type AdapterManifestConfigFieldsType string

// ConnectionListResponse defines model for ConnectionListResponse.
type ConnectionListResponse struct {
	Connections []map[string]interface{} `json:"connections"`
}

// ConnectionResponse defines model for ConnectionResponse.
type ConnectionResponse struct {
	Connection map[string]interface{} `json:"connection"`
}

// CreateConnectionRequest defines model for CreateConnectionRequest.
type CreateConnectionRequest struct {
	AdapterType  string             `json:"adapter_type"`
	Config       *map[string]string `json:"config,omitempty"`
	ConnectionId string             `json:"connection_id"`
	Credential   *struct {
		Ref    *string                                  `json:"ref,omitempty"`
		Source *CreateConnectionRequestCredentialSource `json:"source,omitempty"`
	} `json:"credential,omitempty"`

	// Secret Write-only: accepted on create, sealed at rest, never echoed in any response.
	Secret *string `json:"secret,omitempty"`

	// WorkspaceId Optional. Defaults to the request's authorized workspace.
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// CreateConnectionRequestCredentialSource defines model for CreateConnectionRequest.Credential.Source.
type CreateConnectionRequestCredentialSource string

// CreateRevisionRequest defines model for CreateRevisionRequest.
type CreateRevisionRequest struct {
	Revision map[string]interface{} `json:"revision"`
}

// CreateRunRequest Create a run. The only required input is an image (top-level shorthand) or a full workload spec. run_id is optional and server-generated (uuidv7) when omitted; an Idempotency-Key header is required for retry-safe replay.
type CreateRunRequest struct {
	// Args Container args for the image shorthand.
	Args *[]string `json:"args,omitempty"`

	// Env Run-level literal env bindings. For stored or explicit workload specs, these override or add to the workload container env for this run only. For image shorthand, these become the synthesized container env.
	Env *map[string]EnvBinding `json:"env,omitempty"`

	// Image Top-level image shorthand. Synthesizes the single container when no full workload spec is supplied. Ignored when an explicit workload spec is present.
	Image *string `json:"image,omitempty"`

	// RunId Optional. When omitted the server generates a uuidv7-based run id and returns it.
	RunId *string `json:"run_id,omitempty"`

	// Workload Full workload revision spec. Takes precedence over the image shorthand when both are supplied.
	Workload           *map[string]interface{} `json:"workload,omitempty"`
	WorkloadId         *string                 `json:"workload_id,omitempty"`
	WorkloadRevisionId *string                 `json:"workload_revision_id,omitempty"`
	WorkspaceId        *string                 `json:"workspace_id,omitempty"`
}

// CreateWorkloadRequest defines model for CreateWorkloadRequest.
type CreateWorkloadRequest struct {
	Name        string `json:"name"`
	WorkloadId  string `json:"workload_id"`
	WorkspaceId string `json:"workspace_id"`
}

// EnvBinding defines model for EnvBinding.
type EnvBinding struct {
	Value *string `json:"value,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Events []map[string]interface{} `json:"events"`
}

// OfferListResponse defines model for OfferListResponse.
type OfferListResponse struct {
	Offers []map[string]interface{} `json:"offers"`
}

// PlacementDecisionResponse defines model for PlacementDecisionResponse.
type PlacementDecisionResponse struct {
	Decision map[string]interface{} `json:"decision"`
}

// PlacementPreviewRequest defines model for PlacementPreviewRequest.
type PlacementPreviewRequest struct {
	RunId       *string                `json:"run_id,omitempty"`
	Workload    map[string]interface{} `json:"workload"`
	WorkspaceId *string                `json:"workspace_id,omitempty"`
}

// PlacementPreviewResponse defines model for PlacementPreviewResponse.
type PlacementPreviewResponse struct {
	Decision map[string]interface{} `json:"decision"`
}

// ReplaySinkRequest defines model for ReplaySinkRequest.
type ReplaySinkRequest struct {
	FromExclusive *int    `json:"from_exclusive,omitempty"`
	Limit         *int    `json:"limit,omitempty"`
	ReplayId      *string `json:"replay_id,omitempty"`
}

// ReportRunRequest defines model for ReportRunRequest.
type ReportRunRequest struct {
	Data *map[string]interface{} `json:"data,omitempty"`

	// ExitCode Terminal exit code; when present the broker records the authoritative outcome and requests cleanup.
	ExitCode *int   `json:"exit_code,omitempty"`
	Type     string `json:"type"`
}

// ResolveImageRequest defines model for ResolveImageRequest.
type ResolveImageRequest struct {
	Image    string `json:"image"`
	Platform string `json:"platform"`
}

// ResolveImageResponse defines model for ResolveImageResponse.
type ResolveImageResponse struct {
	Image map[string]interface{} `json:"image"`
}

// Run defines model for Run.
type Run struct {
	// CancelledBy Audited principal of the cancel command. Absent unless a principal-attributed cancel was recorded.
	CancelledBy *string    `json:"cancelled_by,omitempty"`
	Cleanup     RunCleanup `json:"cleanup"`
	Closed      bool       `json:"closed"`

	// CreatedBy Audited principal of the create command: a signed-in operator email, or bearer for machine-token calls. Absent on runs recorded without a principal.
	CreatedBy *string `json:"created_by,omitempty"`

	// Disposition Recorded cleanup disposition. terminate: the run provisioned a host we own that is destroyed on cleanup. release: the run borrowed a slot in a standing pool we do not own; cleanup removes only our job. Recorded at launch time and dispatched on the recorded value, never re-inferred at cleanup time. Absent until a launch intent is recorded.
	Disposition *RunDisposition `json:"disposition,omitempty"`

	// ExitCode Container exit code, surfaced once observed. Absent until a terminal observation is recorded.
	ExitCode           *int        `json:"exit_code,omitempty"`
	Id                 string      `json:"id"`
	Outcome            *RunOutcome `json:"outcome,omitempty"`
	Phase              string      `json:"phase"`
	WorkloadRevisionId *string     `json:"workload_revision_id,omitempty"`
	WorkspaceId        string      `json:"workspace_id"`
}

// RunCleanup defines model for Run.Cleanup.
type RunCleanup string

// RunDisposition Recorded cleanup disposition. terminate: the run provisioned a host we own that is destroyed on cleanup. release: the run borrowed a slot in a standing pool we do not own; cleanup removes only our job. Recorded at launch time and dispatched on the recorded value, never re-inferred at cleanup time. Absent until a launch intent is recorded.
type RunDisposition string

// RunOutcome defines model for Run.Outcome.
type RunOutcome string

// RunListResponse defines model for RunListResponse.
type RunListResponse struct {
	Runs []Run `json:"runs"`
}

// RunResponse defines model for RunResponse.
type RunResponse struct {
	// Duplicate True when this create was a safe idempotent replay of an existing run.
	Duplicate *bool              `json:"duplicate,omitempty"`
	Links     *map[string]string `json:"links,omitempty"`

	// Metadata Reserved for per-response metadata.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Run      Run                     `json:"run"`

	// RunId Convenience top-level run identifier, equal to run.id. Returned on every run response alongside the full run record.
	RunId string `json:"run_id"`
}

// SinkResult defines model for SinkResult.
type SinkResult struct {
	Delivered     int     `json:"delivered"`
	FailedEventId *string `json:"failed_event_id,omitempty"`
	LastPosition  int     `json:"last_position"`
	ReplayId      *string `json:"replay_id,omitempty"`
	SinkId        string  `json:"sink_id"`
}

// SinkStatus defines model for SinkStatus.
type SinkStatus struct {
	Cursor    int    `json:"cursor"`
	HasCursor bool   `json:"has_cursor"`
	SinkId    string `json:"sink_id"`
}

// WorkloadRevisionListResponse defines model for WorkloadRevisionListResponse.
type WorkloadRevisionListResponse struct {
	Revisions []map[string]interface{} `json:"revisions"`
}

// WorkloadRevisionResponse defines model for WorkloadRevisionResponse.
type WorkloadRevisionResponse struct {
	Revision map[string]interface{} `json:"revision"`
}

// ListConnectionsParams defines parameters for ListConnections.
type ListConnectionsParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// CreateConnectionParams defines parameters for CreateConnection.
type CreateConnectionParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// DeleteConnectionParams defines parameters for DeleteConnection.
type DeleteConnectionParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// AuthorizeConnectionParams defines parameters for AuthorizeConnection.
type AuthorizeConnectionParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// ListOffersParams defines parameters for ListOffers.
type ListOffersParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// CreateRunParams defines parameters for CreateRun.
type CreateRunParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// GetRunParams defines parameters for GetRun.
type GetRunParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// CancelRunParams defines parameters for CancelRun.
type CancelRunParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// GetRunDecisionParams defines parameters for GetRunDecision.
type GetRunDecisionParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// ListRunEventsParams defines parameters for ListRunEvents.
type ListRunEventsParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// RefreshRunParams defines parameters for RefreshRun.
type RefreshRunParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// ReportRunParams defines parameters for ReportRun.
type ReportRunParams struct {
	WorkspaceId string `form:"workspace_id" json:"workspace_id"`
}

// WaitRunParams defines parameters for WaitRun.
type WaitRunParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// CreateWorkloadParams defines parameters for CreateWorkload.
type CreateWorkloadParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// ListWorkloadRevisionsParams defines parameters for ListWorkloadRevisions.
type ListWorkloadRevisionsParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// CreateWorkloadRevisionParams defines parameters for CreateWorkloadRevision.
type CreateWorkloadRevisionParams struct {
	WorkspaceId    *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
	IdempotencyKey string  `json:"Idempotency-Key"`
}

// GetWorkloadRevisionParams defines parameters for GetWorkloadRevision.
type GetWorkloadRevisionParams struct {
	WorkspaceId *string `form:"workspace_id,omitempty" json:"workspace_id,omitempty"`
}

// CreateConnectionJSONRequestBody defines body for CreateConnection for application/json ContentType.
type CreateConnectionJSONRequestBody = CreateConnectionRequest

// ResolveImageJSONRequestBody defines body for ResolveImage for application/json ContentType.
type ResolveImageJSONRequestBody = ResolveImageRequest

// PreviewPlacementJSONRequestBody defines body for PreviewPlacement for application/json ContentType.
type PreviewPlacementJSONRequestBody = PlacementPreviewRequest

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// ReportRunJSONRequestBody defines body for ReportRun for application/json ContentType.
type ReportRunJSONRequestBody = ReportRunRequest

// ReplaySinkJSONRequestBody defines body for ReplaySink for application/json ContentType.
type ReplaySinkJSONRequestBody = ReplaySinkRequest

// CreateWorkloadJSONRequestBody defines body for CreateWorkload for application/json ContentType.
type CreateWorkloadJSONRequestBody = CreateWorkloadRequest

// CreateWorkloadRevisionJSONRequestBody defines body for CreateWorkloadRevision for application/json ContentType.
type CreateWorkloadRevisionJSONRequestBody = CreateRevisionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health/live)
	HealthLive(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	HealthReady(w http.ResponseWriter, r *http.Request)

	// (GET /openapi.json)
	GetOpenAPI(w http.ResponseWriter, r *http.Request)

	// (GET /v1/adapters)
	ListAdapters(w http.ResponseWriter, r *http.Request)

	// (GET /v1/connections)
	ListConnections(w http.ResponseWriter, r *http.Request, params ListConnectionsParams)

	// (POST /v1/connections)
	CreateConnection(w http.ResponseWriter, r *http.Request, params CreateConnectionParams)

	// (DELETE /v1/connections/{connection_id})
	DeleteConnection(w http.ResponseWriter, r *http.Request, connectionId string, params DeleteConnectionParams)

	// (POST /v1/connections/{connection_id}/authorize)
	AuthorizeConnection(w http.ResponseWriter, r *http.Request, connectionId string, params AuthorizeConnectionParams)

	// (POST /v1/images:resolve)
	ResolveImage(w http.ResponseWriter, r *http.Request)

	// (GET /v1/offers)
	ListOffers(w http.ResponseWriter, r *http.Request, params ListOffersParams)

	// (POST /v1/placements:preview)
	PreviewPlacement(w http.ResponseWriter, r *http.Request)

	// (GET /v1/runs)
	ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams)

	// (POST /v1/runs)
	CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams)

	// (GET /v1/runs/{run_id})
	GetRun(w http.ResponseWriter, r *http.Request, runId string, params GetRunParams)

	// (POST /v1/runs/{run_id}/cancel)
	CancelRun(w http.ResponseWriter, r *http.Request, runId string, params CancelRunParams)

	// (GET /v1/runs/{run_id}/decision)
	GetRunDecision(w http.ResponseWriter, r *http.Request, runId string, params GetRunDecisionParams)

	// (GET /v1/runs/{run_id}/events)
	ListRunEvents(w http.ResponseWriter, r *http.Request, runId string, params ListRunEventsParams)

	// (POST /v1/runs/{run_id}/refresh)
	RefreshRun(w http.ResponseWriter, r *http.Request, runId string, params RefreshRunParams)

	// (POST /v1/runs/{run_id}/report)
	ReportRun(w http.ResponseWriter, r *http.Request, runId string, params ReportRunParams)

	// (GET /v1/runs/{run_id}/wait)
	WaitRun(w http.ResponseWriter, r *http.Request, runId string, params WaitRunParams)

	// (GET /v1/sinks/{sink_id})
	GetSinkStatus(w http.ResponseWriter, r *http.Request, sinkId string)

	// (POST /v1/sinks/{sink_id}/deliver)
	DeliverSink(w http.ResponseWriter, r *http.Request, sinkId string)

	// (POST /v1/sinks/{sink_id}/replay)
	ReplaySink(w http.ResponseWriter, r *http.Request, sinkId string)

	// (POST /v1/workloads)
	CreateWorkload(w http.ResponseWriter, r *http.Request, params CreateWorkloadParams)

	// (GET /v1/workloads/{workload_id}/revisions)
	ListWorkloadRevisions(w http.ResponseWriter, r *http.Request, workloadId string, params ListWorkloadRevisionsParams)

	// (POST /v1/workloads/{workload_id}/revisions)
	CreateWorkloadRevision(w http.ResponseWriter, r *http.Request, workloadId string, params CreateWorkloadRevisionParams)

	// (GET /v1/workloads/{workload_id}/revisions/{revision_id})
	GetWorkloadRevision(w http.ResponseWriter, r *http.Request, workloadId string, revisionId string, params GetWorkloadRevisionParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthLive operation middleware
func (siw *ServerInterfaceWrapper) HealthLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthReady operation middleware
func (siw *ServerInterfaceWrapper) HealthReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenAPI operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPI(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenAPI(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdapters operation middleware
func (siw *ServerInterfaceWrapper) ListAdapters(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdapters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListConnections operation middleware
func (siw *ServerInterfaceWrapper) ListConnections(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConnectionsParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListConnections(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateConnection operation middleware
func (siw *ServerInterfaceWrapper) CreateConnection(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateConnectionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConnection(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteConnection operation middleware
func (siw *ServerInterfaceWrapper) DeleteConnection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connection_id" -------------
	var connectionId string

	err = runtime.BindStyledParameterWithOptions("simple", "connection_id", r.PathValue("connection_id"), &connectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connection_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteConnectionParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteConnection(w, r, connectionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthorizeConnection operation middleware
func (siw *ServerInterfaceWrapper) AuthorizeConnection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connection_id" -------------
	var connectionId string

	err = runtime.BindStyledParameterWithOptions("simple", "connection_id", r.PathValue("connection_id"), &connectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connection_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthorizeConnectionParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthorizeConnection(w, r, connectionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveImage operation middleware
func (siw *ServerInterfaceWrapper) ResolveImage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveImage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOffers operation middleware
func (siw *ServerInterfaceWrapper) ListOffers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOffersParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOffers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewPlacement operation middleware
func (siw *ServerInterfaceWrapper) PreviewPlacement(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewPlacement(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRuns operation middleware
func (siw *ServerInterfaceWrapper) ListRuns(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", r.PathValue("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRunParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelRun operation middleware
func (siw *ServerInterfaceWrapper) CancelRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", r.PathValue("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CancelRunParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunDecision operation middleware
func (siw *ServerInterfaceWrapper) GetRunDecision(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", r.PathValue("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRunDecisionParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunDecision(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunEvents operation middleware
func (siw *ServerInterfaceWrapper) ListRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", r.PathValue("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunEventsParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshRun operation middleware
func (siw *ServerInterfaceWrapper) RefreshRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", r.PathValue("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshRunParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportRun operation middleware
func (siw *ServerInterfaceWrapper) ReportRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", r.PathValue("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ReportRunParams

	// ------------- Required query parameter "workspace_id" -------------

	if paramValue := r.URL.Query().Get("workspace_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "workspace_id"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WaitRun operation middleware
func (siw *ServerInterfaceWrapper) WaitRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", r.PathValue("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params WaitRunParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WaitRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSinkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSinkStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sink_id" -------------
	var sinkId string

	err = runtime.BindStyledParameterWithOptions("simple", "sink_id", r.PathValue("sink_id"), &sinkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sink_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSinkStatus(w, r, sinkId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeliverSink operation middleware
func (siw *ServerInterfaceWrapper) DeliverSink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sink_id" -------------
	var sinkId string

	err = runtime.BindStyledParameterWithOptions("simple", "sink_id", r.PathValue("sink_id"), &sinkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sink_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeliverSink(w, r, sinkId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaySink operation middleware
func (siw *ServerInterfaceWrapper) ReplaySink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sink_id" -------------
	var sinkId string

	err = runtime.BindStyledParameterWithOptions("simple", "sink_id", r.PathValue("sink_id"), &sinkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sink_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaySink(w, r, sinkId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkload operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateWorkloadParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkload(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkloadRevisions operation middleware
func (siw *ServerInterfaceWrapper) ListWorkloadRevisions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workload_id" -------------
	var workloadId string

	err = runtime.BindStyledParameterWithOptions("simple", "workload_id", r.PathValue("workload_id"), &workloadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workload_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkloadRevisionsParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkloadRevisions(w, r, workloadId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkloadRevision operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkloadRevision(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workload_id" -------------
	var workloadId string

	err = runtime.BindStyledParameterWithOptions("simple", "workload_id", r.PathValue("workload_id"), &workloadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workload_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateWorkloadRevisionParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkloadRevision(w, r, workloadId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkloadRevision operation middleware
func (siw *ServerInterfaceWrapper) GetWorkloadRevision(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workload_id" -------------
	var workloadId string

	err = runtime.BindStyledParameterWithOptions("simple", "workload_id", r.PathValue("workload_id"), &workloadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workload_id", Err: err})
		return
	}

	// ------------- Path parameter "revision_id" -------------
	var revisionId string

	err = runtime.BindStyledParameterWithOptions("simple", "revision_id", r.PathValue("revision_id"), &revisionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "revision_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkloadRevisionParams

	// ------------- Optional query parameter "workspace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "workspace_id", r.URL.Query(), &params.WorkspaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkloadRevision(w, r, workloadId, revisionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health/live", wrapper.HealthLive)
	m.HandleFunc("GET "+options.BaseURL+"/health/ready", wrapper.HealthReady)
	m.HandleFunc("GET "+options.BaseURL+"/openapi.json", wrapper.GetOpenAPI)
	m.HandleFunc("GET "+options.BaseURL+"/v1/adapters", wrapper.ListAdapters)
	m.HandleFunc("GET "+options.BaseURL+"/v1/connections", wrapper.ListConnections)
	m.HandleFunc("POST "+options.BaseURL+"/v1/connections", wrapper.CreateConnection)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/connections/{connection_id}", wrapper.DeleteConnection)
	m.HandleFunc("POST "+options.BaseURL+"/v1/connections/{connection_id}/authorize", wrapper.AuthorizeConnection)
	m.HandleFunc("POST "+options.BaseURL+"/v1/images:resolve", wrapper.ResolveImage)
	m.HandleFunc("GET "+options.BaseURL+"/v1/offers", wrapper.ListOffers)
	m.HandleFunc("POST "+options.BaseURL+"/v1/placements:preview", wrapper.PreviewPlacement)
	m.HandleFunc("GET "+options.BaseURL+"/v1/runs", wrapper.ListRuns)
	m.HandleFunc("POST "+options.BaseURL+"/v1/runs", wrapper.CreateRun)
	m.HandleFunc("GET "+options.BaseURL+"/v1/runs/{run_id}", wrapper.GetRun)
	m.HandleFunc("POST "+options.BaseURL+"/v1/runs/{run_id}/cancel", wrapper.CancelRun)
	m.HandleFunc("GET "+options.BaseURL+"/v1/runs/{run_id}/decision", wrapper.GetRunDecision)
	m.HandleFunc("GET "+options.BaseURL+"/v1/runs/{run_id}/events", wrapper.ListRunEvents)
	m.HandleFunc("POST "+options.BaseURL+"/v1/runs/{run_id}/refresh", wrapper.RefreshRun)
	m.HandleFunc("POST "+options.BaseURL+"/v1/runs/{run_id}/report", wrapper.ReportRun)
	m.HandleFunc("GET "+options.BaseURL+"/v1/runs/{run_id}/wait", wrapper.WaitRun)
	m.HandleFunc("GET "+options.BaseURL+"/v1/sinks/{sink_id}", wrapper.GetSinkStatus)
	m.HandleFunc("POST "+options.BaseURL+"/v1/sinks/{sink_id}/deliver", wrapper.DeliverSink)
	m.HandleFunc("POST "+options.BaseURL+"/v1/sinks/{sink_id}/replay", wrapper.ReplaySink)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workloads", wrapper.CreateWorkload)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads/{workload_id}/revisions", wrapper.ListWorkloadRevisions)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workloads/{workload_id}/revisions", wrapper.CreateWorkloadRevision)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads/{workload_id}/revisions/{revision_id}", wrapper.GetWorkloadRevision)

	return m
}
