/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOpenAPI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/wait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["waitRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRunDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/placements:preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewPlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnections"];
        put?: never;
        post: operations["createConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Append the deleted fact and remove the sealed credential blob. The event stream is retained; the id cannot be reused — recreate under a fresh id. */
        delete: operations["deleteConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{connection_id}/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authorizeConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Registered provider adapters' onboarding manifests: display metadata, config fields, credential expectations, and ordered setup steps. Static per process; no workspace scoping. */
        get: operations["listAdapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Workload-facing report ingest. Authenticated with the per-run bearer token injected as MERCATOR_RUN_TOKEN (not the operator token). */
        post: operations["reportRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWorkload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workloads/{workload_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkloadRevisions"];
        put?: never;
        post: operations["createWorkloadRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workloads/{workload_id}/revisions/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkloadRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images:resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{sink_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSinkStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{sink_id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deliverSink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{sink_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replaySink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Create a run. The only required input is an image (top-level shorthand) or a full workload spec. run_id is optional and server-generated (uuidv7) when omitted; an Idempotency-Key header is required for retry-safe replay. */
        CreateRunRequest: {
            workspace_id?: string;
            /** @description Optional. When omitted the server generates a uuidv7-based run id and returns it. */
            run_id?: string;
            workload_id?: string;
            workload_revision_id?: string;
            /** @description Top-level image shorthand. Synthesizes the single container when no full workload spec is supplied. Ignored when an explicit workload spec is present. */
            image?: string;
            /** @description Container args for the image shorthand. */
            args?: string[];
            /** @description Run-level literal env bindings. For stored or explicit workload specs, these override or add to the workload container env for this run only. For image shorthand, these become the synthesized container env. */
            env?: {
                [key: string]: components["schemas"]["EnvBinding"];
            };
            workload?: components["schemas"]["WorkloadRevision"];
        };
        CleanupError: {
            code: string;
            message: string;
            retryable: boolean;
            launch_key: string;
            /** @enum {string} */
            disposition: "release" | "terminate";
        };
        Run: {
            id: string;
            workspace_id: string;
            workload_revision_id: string;
            phase: string;
            /** @enum {string} */
            outcome?: "succeeded" | "failed" | "cancelled";
            exit_code?: number;
            /** @enum {string} */
            cleanup: "not_required" | "pending" | "confirmed" | "blocked";
            /** @enum {string} */
            disposition?: "release" | "terminate";
            cleanup_error?: components["schemas"]["CleanupError"];
            closed: boolean;
            created_by?: string;
            cancelled_by?: string;
        };
        CreateWorkloadRequest: {
            workspace_id: string;
            workload_id: string;
            name: string;
        };
        CreateRevisionRequest: {
            revision: components["schemas"]["WorkloadRevision"];
        };
        WorkloadRevisionResponse: {
            revision: components["schemas"]["WorkloadRevision"];
        };
        WorkloadRevisionListResponse: {
            revisions: components["schemas"]["WorkloadRevision"][];
        };
        ResolveImageRequest: {
            image: string;
            platform: string;
        };
        ResolveImageResponse: {
            image: components["schemas"]["ResolvedImage"];
        };
        EnvBinding: {
            value?: string;
        };
        RunResponse: {
            /** @description Convenience top-level run identifier, equal to run.id. Returned on every run response alongside the full run record. */
            run_id: string;
            run: components["schemas"]["Run"];
            /** @description Reserved for per-response metadata. */
            metadata?: {
                [key: string]: unknown;
            };
            links?: {
                [key: string]: string;
            };
            /** @description True when this create was a safe idempotent replay of an existing run. */
            duplicate?: boolean;
        };
        RunListResponse: {
            runs: components["schemas"]["Run"][];
        };
        EventListResponse: {
            events: components["schemas"]["CloudEvent"][];
        };
        PlacementPreviewRequest: {
            run_id?: string;
            workspace_id?: string;
            workload: components["schemas"]["WorkloadRevision"];
        };
        PlacementPreviewResponse: {
            decision: components["schemas"]["PlacementDecision"];
        };
        PlacementDecisionResponse: {
            decision: components["schemas"]["PlacementDecision"];
        };
        AdapterListResponse: {
            adapters: components["schemas"]["AdapterManifest"][];
        };
        /** @description An adapter's self-description for onboarding surfaces. Lives next to the adapter's code; carries no per-connection state and never any secret material. */
        AdapterManifest: {
            /** @description Adapter type string used as adapter_type at connection create time. */
            type: string;
            display_name: string;
            /** @description Well-known slug the console maps to a bundled logomark asset; consumers fall back to a typographic monogram. */
            logo: string;
            description: string;
            credential: {
                required: boolean;
                label?: string;
                /** @description One-line hint about the expected token shape or scope. */
                format?: string;
            };
            config_fields: {
                name: string;
                label: string;
                /** @enum {string} */
                type: "string" | "bool" | "int";
                required: boolean;
                /** @description Mask in UIs and never echo after save. */
                secret?: boolean;
                default?: string;
                placeholder?: string;
                help?: string;
            }[];
            /** @description Ordered how-do-I-get-a-credential walkthrough; text is UI copy. */
            setup_steps: {
                text: string;
                url?: string;
            }[];
        };
        ConnectionListResponse: {
            connections: components["schemas"]["ConnectionRecord"][];
        };
        CreateConnectionRequest: {
            /** @description Optional. Defaults to the request's authorized workspace. */
            workspace_id?: string;
            connection_id: string;
            adapter_type: string;
            config?: {
                [key: string]: string;
            };
            credential?: components["schemas"]["Credential"];
            /** @description Write-only: accepted on create, sealed at rest, never echoed in any response. */
            secret?: string;
        };
        ConnectionResponse: {
            connection: components["schemas"]["ConnectionRecord"];
        };
        ReportRunRequest: {
            /** @description Report kind. The reserved exit kind is terminal and requires exit_code; every other kind is nonterminal and must omit exit_code. */
            type: string;
            data?: {
                [key: string]: unknown;
            };
            /** @description Required when type is exit and forbidden for every other report type. The broker records the authoritative outcome and requests cleanup. */
            exit_code?: number;
        };
        ConnectionFailure: {
            connection_id: string;
            adapter_type: string;
            message: string;
        };
        OfferListResponse: {
            offers: components["schemas"]["OfferSnapshot"][];
            failures: components["schemas"]["ConnectionFailure"][];
        };
        ReplaySinkRequest: {
            from_exclusive?: number;
            limit?: number;
            replay_id?: string;
        };
        SinkResult: {
            sink_id: string;
            delivered: number;
            last_position: number;
            failed_event_id?: string;
            replay_id?: string;
        };
        SinkStatus: {
            sink_id: string;
            cursor: number;
            has_cursor: boolean;
        };
        ErrorResponse: {
            code: string;
            message: string;
            details?: components["schemas"]["Violation"][];
        };
        Platform: {
            os: string;
            architecture: string;
        };
        PortSpec: {
            name: string;
            container_port: number;
            protocol: string;
            /** @enum {string} */
            exposure: "none" | "public" | "private";
        };
        ContainerSpec: {
            name: string;
            image: string;
            platform: components["schemas"]["Platform"];
            entrypoint?: string[];
            args?: string[];
            env?: {
                [key: string]: components["schemas"]["EnvBinding"];
            };
            ports?: components["schemas"]["PortSpec"][];
        };
        CPURequirement: {
            /** Format: int64 */
            min_millis: number;
        };
        MemoryRequirement: {
            /** Format: int64 */
            min_bytes: number;
        };
        DiskRequirement: {
            /** Format: int64 */
            min_bytes: number;
        };
        AcceleratorRequirement: {
            vendor: string;
            model_any_of?: string[];
            count: number;
            /** Format: int64 */
            memory_min_bytes: number;
        };
        ResourceRequirements: {
            cpu: components["schemas"]["CPURequirement"];
            memory: components["schemas"]["MemoryRequirement"];
            accelerators?: components["schemas"]["AcceleratorRequirement"][];
            ephemeral_disk: components["schemas"]["DiskRequirement"];
        };
        NetworkDownloadRequirement: {
            /** @enum {string} */
            scope: "registry" | "public_internet";
            /** Format: double */
            min_p10_mbps: number;
            /** Format: int64 */
            max_measurement_age_seconds: number;
            allow_unknown: boolean;
        };
        NetworkRequirements: {
            /** @enum {string} */
            inbound: "none" | "public_port";
            download?: components["schemas"]["NetworkDownloadRequirement"];
        };
        PlacementPolicy: {
            /** @enum {string} */
            objective: "cheapest" | "fastest_start" | "fastest_completion" | "balanced";
            /** Format: double */
            max_p90_start_seconds?: number;
            /** Format: double */
            expected_runtime_seconds?: number;
            /** Format: double */
            max_expected_cost_usd?: number;
            allow_unknown_pricing?: boolean;
        };
        ExecutionPolicy: {
            /** Format: int64 */
            max_runtime_seconds: number;
            max_pre_start_attempts: number;
        };
        WorkloadSpec: {
            containers: components["schemas"]["ContainerSpec"][];
            resources: components["schemas"]["ResourceRequirements"];
            network: components["schemas"]["NetworkRequirements"];
            placement: components["schemas"]["PlacementPolicy"];
            execution: components["schemas"]["ExecutionPolicy"];
            metadata?: {
                [key: string]: string;
            };
            raw?: {
                [key: string]: unknown;
            };
        };
        WorkloadRevision: {
            id: string;
            workspace_id: string;
            workload_id: string;
            digest: string;
            spec: components["schemas"]["WorkloadSpec"];
        };
        Violation: {
            code: string;
            path: string;
            required?: unknown;
            offered?: unknown;
            message: string;
        };
        AcceleratorInventory: {
            vendor: string;
            model: string;
            canonical_model?: string;
            count: number;
            /** Format: int64 */
            memory_bytes: number;
        };
        ResourceInventory: {
            /** Format: int64 */
            cpu_millis: number;
            /** Format: int64 */
            memory_bytes: number;
            /** Format: int64 */
            ephemeral_disk_bytes: number;
            accelerators?: components["schemas"]["AcceleratorInventory"][];
        };
        ContainerCapabilities: {
            max_containers: number;
            supports_digest_refs: boolean;
            supports_entrypoint_override: boolean;
            max_environment_bytes: number;
        };
        LifecycleCapabilities: {
            idempotent_launch: string;
            list_owned: boolean;
            provider_ttl: boolean;
            cancel_queued: boolean;
        };
        ResourceCapabilities: {
            gpu_vendors?: string[];
        };
        NetworkCapabilities: {
            /** @enum {string} */
            inbound: "none" | "public_port";
            protocols?: string[];
            public_ipv4: boolean;
        };
        PricingCapabilities: {
            known: boolean;
        };
        ObservabilityCapabilities: {
            logs: string;
            metrics: string;
            shell: string;
        };
        CapabilityProfile: {
            offer_kinds?: ("standing" | "provisionable")[];
            container: components["schemas"]["ContainerCapabilities"];
            lifecycle: components["schemas"]["LifecycleCapabilities"];
            resources: components["schemas"]["ResourceCapabilities"];
            network: components["schemas"]["NetworkCapabilities"];
            pricing: components["schemas"]["PricingCapabilities"];
            observability: components["schemas"]["ObservabilityCapabilities"];
        };
        NetworkFact: {
            /** @enum {string} */
            scope: "registry" | "public_internet";
            statistic: string;
            /** Format: double */
            value_mbps: number;
            source: string;
            sample_count: number;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            valid_until: string;
            /** Format: double */
            confidence: number;
        };
        NetworkFacts: {
            download?: components["schemas"]["NetworkFact"][];
        };
        PriceModel: {
            currency: string;
            /** Format: double */
            setup_fee_usd: number;
            /** Format: double */
            rate_per_second_usd: number;
            /** Format: int64 */
            minimum_charge_seconds: number;
            /** Format: int64 */
            granularity_seconds: number;
            known: boolean;
        };
        QueueSnapshot: {
            /** Format: double */
            queued_work_seconds: number;
            active_slots: number;
        };
        Estimate: {
            /** Format: double */
            p50?: number;
            /** Format: double */
            p90?: number;
            /** Format: double */
            expected?: number;
            /** Format: double */
            confidence?: number;
            source?: string;
            sample_count?: number;
            model_version?: string;
        };
        ImageCacheEvidence: {
            manifest_cached: boolean;
            /** Format: int64 */
            missing_bytes: number;
            known: boolean;
        };
        CapacityEvidence: {
            available: boolean;
            /** Format: double */
            confidence: number;
        };
        ReliabilityEvidence: {
            /** Format: double */
            start_failure_rate?: number;
            /** Format: double */
            interruption_rate?: number;
            /** Format: double */
            confidence?: number;
        };
        OfferSnapshot: {
            id: string;
            connection_id: string;
            adapter_type: string;
            /** @enum {string} */
            kind: "standing" | "provisionable";
            native_ref: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            expires_at: string;
            platform: components["schemas"]["Platform"];
            resources: components["schemas"]["ResourceInventory"];
            capabilities: components["schemas"]["CapabilityProfile"];
            network: components["schemas"]["NetworkFacts"];
            pricing: components["schemas"]["PriceModel"];
            queue?: components["schemas"]["QueueSnapshot"];
            provisioning?: components["schemas"]["Estimate"];
            image_cache: components["schemas"]["ImageCacheEvidence"];
            capacity: components["schemas"]["CapacityEvidence"];
            reliability: components["schemas"]["ReliabilityEvidence"];
        };
        CollectionReport: {
            connections_queried?: string[];
            connections_from_cache?: string[];
            excluded_connections?: string[];
        };
        CandidateEstimates: {
            queue_seconds: components["schemas"]["Estimate"];
            provision_seconds: components["schemas"]["Estimate"];
            pull_seconds: components["schemas"]["Estimate"];
            start_seconds: components["schemas"]["Estimate"];
            cost_usd: components["schemas"]["Estimate"];
        };
        CandidateDecision: {
            offer_snapshot_id: string;
            connection_id?: string;
            adapter_type?: string;
            native_ref?: string;
            feasible: boolean;
            rejections?: components["schemas"]["Violation"][];
            estimates: components["schemas"]["CandidateEstimates"];
            /** Format: double */
            score_usd?: number;
        };
        PlacementDecision: {
            id: string;
            run_id?: string;
            workload_revision_digest: string;
            /** Format: date-time */
            evaluated_at: string;
            model_version: string;
            policy: components["schemas"]["PlacementPolicy"];
            collection_report: components["schemas"]["CollectionReport"];
            candidates: components["schemas"]["CandidateDecision"][];
            selected_offer_snapshot_id?: string;
            selection_reason_codes: string[];
        };
        CloudEvent: {
            specversion: string;
            id: string;
            source: string;
            type: string;
            subject: string;
            /** Format: date-time */
            time: string;
            workspaceid: string;
            /** Format: int64 */
            streamversion: number;
            /** Format: int64 */
            globalposition: number;
            correlationid?: string;
            causationid?: string;
            data: unknown;
        };
        Credential: {
            /** @enum {string} */
            source: "env" | "mercator";
            ref: string;
        };
        ConnectionRecord: {
            id: string;
            workspace_id: string;
            adapter_type: string;
            authorization_schema?: {
                [key: string]: string;
            };
            authorized: boolean;
            config?: {
                [key: string]: string;
            };
            credential?: components["schemas"]["Credential"];
            created_by?: string;
            authorized_by?: string;
        };
        ResolvedImage: {
            image: string;
            digest: string;
            platform: string;
            already_pinned?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    getOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Run request accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description IdempotencyConflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    waitRun: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Error response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshRun: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRunEvents: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRunDecision: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Placement decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementDecisionResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    previewPlacement: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementPreviewRequest"];
            };
        };
        responses: {
            /** @description Placement decision preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementPreviewResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Offer query failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listConnections: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionListResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createConnection: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionRequest"];
            };
        };
        responses: {
            /** @description Connection created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteConnection: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    authorizeConnection: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection verified and authorized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Connection verification failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAdapters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Adapter manifest list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterListResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reportRun: {
        parameters: {
            query: {
                workspace_id: string;
            };
            header?: {
                /** @description Per-run bearer token issued in the launch reporting environment. */
                Authorization?: string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRunRequest"];
            };
        };
        responses: {
            /** @description Report recorded */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        recorded: boolean;
                    };
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid run token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Terminal report conflicts with the report already recorded for this run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listOffers: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offer list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferListResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createWorkload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkloadRequest"];
            };
        };
        responses: {
            /** @description Workload created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workload_id: string;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkloadRevisions: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                workload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workload revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadRevisionListResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createWorkloadRevision: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header: {
                "Idempotency-Key": string;
            };
            path: {
                workload_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRevisionRequest"];
            };
        };
        responses: {
            /** @description Workload revision created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadRevisionResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getWorkloadRevision: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                workload_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workload revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadRevisionResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resolveImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveImageRequest"];
            };
        };
        responses: {
            /** @description Resolved image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveImageResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSinkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sink status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SinkStatus"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sink not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deliverSink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sink delivery result */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SinkResult"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sink delivery failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replaySink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaySinkRequest"];
            };
        };
        responses: {
            /** @description Sink replay result */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SinkResult"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sink replay failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
